<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE piece [
  <!ELEMENT piece (titre, acte+)>
  <!ATTLIST piece xml:lang CDATA #REQUIRED>
  <!ELEMENT acte (titre, scene+)>
  <!ELEMENT scene (titre, casting, (tourDeParole, vers+)+)>
  <!ELEMENT titre (#PCDATA)>
  <!ELEMENT casting (#PCDATA)>
  <!ELEMENT tourDeParole (#PCDATA | didascalie)*>
  <!ELEMENT didascalie (#PCDATA)>
  <!ELEMENT vers (#PCDATA)>
  <!ATTLIST vers n CDATA #IMPLIED>
  <!ATTLIST vers part (I|F) #IMPLIED>
]>

<piece xml:lang="fr">
  <titre>LE MISANTHROPE.</titre>
  <acte>
    <titre>ACTE PREMIER</titre>
    <scene>
      <titre>SCÈNE 1.</titre>
      <casting>PHILINTE, ALCESTE</casting>
      <tourDeParole>PHILINTE.</tourDeParole>
      <vers n="1" part="I">Qu'est-ce donc? qu'avez-vous ?</vers>
      <tourDeParole>ALCESTE<didascalie>, assis</didascalie>.</tourDeParole>
      <vers n="1" part="F">Laissez-moi, je vous prie.</vers>
      <tourDeParole>PHILINTE.</tourDeParole>
      <vers>Mais encor, dites-moi, quelle bizarrerie....</vers>
      <tourDeParole>ALCESTE.</tourDeParole>
      <vers>Laissez-moi là, vous dis-je, et courez vous cacher.</vers>
      <tourDeParole>PHILINTE.</tourDeParole>
      <vers>Mais on entend les gens au moins sans se fâcher.</vers>
      <tourDeParole>ALCESTE.</tourDeParole>
      <vers>Moi, je veux me fâcher, et ne veux point entendre.</vers>
      <tourDeParole>PHILINTE</tourDeParole>
      <vers>Dans vos brusques chagrins je ne puis vous comprendre,</vers>
      <vers>Et quoique amis enfin, je suis tout des premiers....</vers>
      <tourDeParole>ALCESTE<didascalie>, se levant brusquement</didascalie>.</tourDeParole>
      <vers>Moi, votre ami? Rayez cela de vos papiers.</vers>
      <vers>J'ai fait jusques ici profession de l'être,</vers>
      <vers>Mais, après ce qu'en vous je viens de voir paraître,</vers>
    </scene>
  </acte>
</piece>